const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,DB=path.join(__dirname,'data.json'),SOS_DIR=path.join(__dirname,'sos_live');
if(!fs.existsSync(SOS_DIR))fs.mkdirSync(SOS_DIR,{recursive:true});
function read(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch(e){return {complaints:[]}}}
function write(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function send(res,code,data,type='application/json'){res.writeHead(code,{'Content-Type':type,'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});res.end(type.includes('json')?JSON.stringify(data):data)}
function body(req){return new Promise((ok,fail)=>{let s='';req.on('data',c=>{s+=c;if(s.length>12*1024*1024)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){fail(e)}})})}
function forwardPolice(payload){return new Promise(resolve=>{const target=process.env.POLICE_LIVE_ENDPOINT;if(!target)return resolve(false);try{const u=new URL(target),lib=u.protocol==='https:'?https:http;const req=lib.request({method:'POST',hostname:u.hostname,port:u.port||undefined,path:u.pathname+u.search,headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(JSON.stringify(payload))}},r=>{r.resume();resolve(r.statusCode>=200&&r.statusCode<300)});req.on('error',()=>resolve(false));req.write(JSON.stringify(payload));req.end()}catch(e){resolve(false)}})}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return send(res,204,'');try{
if(req.url==='/api/health'&&req.method==='GET')return send(res,200,{ok:true,service:'VAJRA NYAY BACKEND',policeLiveConfigured:!!process.env.POLICE_LIVE_ENDPOINT,time:new Date().toISOString()});
if(req.url==='/api/sos/chunk'&&req.method==='POST'){const x=await body(req);if(!x.sessionId||!x.videoBase64)return send(res,400,{ok:false,error:'Missing SOS chunk'});const safe=String(x.sessionId).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);const dir=path.join(SOS_DIR,safe);if(!fs.existsSync(dir))fs.mkdirSync(dir,{recursive:true});const raw=Buffer.from(x.videoBase64,'base64');const hash=crypto.createHash('sha256').update(raw).digest('hex');const fn=String(Number.isFinite(Number(x.chunkIndex))?x.chunkIndex:0).padStart(8,'0')+'.webm';fs.writeFileSync(path.join(dir,fn),raw);fs.writeFileSync(path.join(dir,'manifest.jsonl'),JSON.stringify({sessionId:safe,chunkIndex:x.chunkIndex,sha256:hash,createdAt:x.createdAt,lat:x.lat??null,lng:x.lng??null,mimeType:x.mimeType||'video/webm'})+'\n',{flag:'a'});const forwarded=await forwardPolice({...x,sha256:hash});return send(res,201,{ok:true,stored:true,sha256:hash,forwarded});}
if(req.url.startsWith('/api/complaints')&&req.method==='GET'){const d=read(),q=new URL(req.url,'http://localhost').searchParams.get('q')?.toLowerCase()||'';return send(res,200,d.complaints.filter(x=>!q||String(x.id).toLowerCase().includes(q)||String(x.category||'').toLowerCase().includes(q)))}
if(req.url==='/api/complaints'&&req.method==='POST'){const x=await body(req),d=read();const i=d.complaints.findIndex(v=>v.id===x.id);if(i>=0)d.complaints[i]={...d.complaints[i],...x};else d.complaints.push(x);write(d);return send(res,201,{ok:true,complaint:x})}
if(req.url.startsWith('/api/complaints/')&&req.method==='GET'){const id=decodeURIComponent(req.url.split('/').pop()),x=read().complaints.find(v=>v.id===id);return x?send(res,200,x):send(res,404,{ok:false,error:'Case not found'})}
if(req.method==='GET'&&(req.url==='/'||req.url==='/index.html')){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(__dirname,'index.html')).pipe(res)}
send(res,404,{ok:false,error:'Not found'})}catch(e){send(res,500,{ok:false,error:e.message})}});
server.listen(PORT,()=>console.log(`VAJRA NYAY: http://localhost:${PORT}`));
